# Generated by Django 5.0.6 on 2024-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13)),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_stock', models.PositiveIntegerField(default=models.PositiveIntegerField(default=1))),
            ],
        ),
    ]
