# Generated by Django 5.0.6 on 2024-05-23 15:20

import book.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=book.models.get_due_date, editable=False),
        ),
    ]
